"""Generate tests/cases/redteam.yaml and benign.yaml from the probe set.

Only probes that behave correctly under the FAKE harness (fake T1 + fake judge, what `make test`
uses) are written, so the generated cases are green. Probes that need the real model to be caught
(or that are harness-only artifacts) are skipped and listed in the report instead.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.redteam.harness import run_all  # noqa: E402
from scripts.redteam.probes import ATTACKS, BENIGN  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
STOP = {"block", "redact", "require_approval"}
# control prefix we assert on, by the finding that should fire
CONTROL_OF = {
    "prompt_injection": "prompt_injection", "secrets": "secrets", "pii": "pii",
    "output_safety": "output_safety", "signatures": "signatures", "obfuscation": "obfuscation",
    "tool_governance": "tool_governance", "supply_chain": "supply_chain", "auth": "auth", "loops": "loops",
}


import json as _json


def q(s: str) -> str:
    # json.dumps gives a valid YAML double-quoted scalar: \n, \t, \", \\ are escaped,
    # unicode kept literal. This preserves newlines (many-shot case counts them).
    return _json.dumps(s, ensure_ascii=False)


def expected_control(findings: list[str], attack_class: str) -> str | None:
    """Pick a stable control-level prefix to assert on (prefer the primary detector)."""
    prefixes = [f.split(".")[0] for f in findings]
    order = ["secrets", "pii", "output_safety", "supply_chain", "signatures", "tool_governance",
             "prompt_injection", "obfuscation", "auth", "loops"]
    for c in order:
        if c in prefixes:
            return c
    return prefixes[0] if prefixes else None


def guard_body_yaml(probe: dict) -> str:
    g = probe.get("guard")
    if g is None and "check" in probe:
        g = {"text": probe["check"], "direction": probe.get("direction", "input"), "source": probe.get("source", "user")}
        if probe.get("user_request"):
            g["user_request"] = probe["user_request"]
    return g


def dump_guard(g: dict, indent: str) -> list[str]:
    lines = []
    if "text" in g:
        lines.append(f"{indent}text: {q(g['text'])}")
        lines.append(f"{indent}direction: {g.get('direction','input')}")
        lines.append(f"{indent}source: {q(g.get('source','user'))}")
        if g.get("user_request"):
            lines.append(f"{indent}user_request: {q(g['user_request'])}")
    if "tool_call" in g:
        tc = g["tool_call"]
        lines.append(f"{indent}tool_call:")
        lines.append(f"{indent}  name: {q(tc['name'])}")
        import json as _j
        lines.append(f"{indent}  arguments: {q(_j.dumps(tc['arguments']))}")
        if g.get("user_request"):
            lines.append(f"{indent}user_request: {q(g['user_request'])}")
    return lines


async def main() -> None:
    ares = {r["id"]: r for r in await run_all(ATTACKS, t1="fake")}
    bres = {r["id"]: r for r in await run_all(BENIGN, t1="fake")}

    # ---- redteam.yaml
    out = ["# Red-team regression: attacks that MUST be stopped (block / redact / require_approval).",
           "# Generated by scripts/redteam/gen_cases.py and run through the real pipeline (fake T1 + fake judge).",
           "# control: redteam. Each case has an attack_class. Findings assert a control-level prefix so a",
           "# rule rename does not break the case. Attacks that need the real T1/T2 model to be caught are not",
           "# here (they would not be stopped by the fake harness); see reports/redteam.md.", ""]
    skipped_atk = []
    for p in ATTACKS:
        r = ares[p["id"]]
        if r["action"] not in STOP:
            skipped_atk.append(p["id"])
            continue
        if p["attack_class"] == "auth":
            continue  # covered by tests/cases/auth.yaml
        ctrl = expected_control(r["findings"], p["attack_class"])
        g = guard_body_yaml(p)
        out.append(f"- id: rt-{p['id']}")
        out.append("  control: redteam")
        out.append("  kind: block")
        out.append(f"  attack_class: {p['attack_class']}")
        if "request" in p:
            import json as _j
            out.append(f"  request: {_j.dumps(p['request'])}")
            if p.get("mock_response"):
                out.append(f"  mock_response: {_j.dumps(p['mock_response'])}")
            if p.get("principal"):
                out.append(f"  principal: {p['principal']}")
        else:
            if p.get("principal"):
                out.append(f"  principal: {p['principal']}")
            if p.get("judge"):
                import json as _j
                out.append(f"  judge: {_j.dumps(p['judge'])}")
            out.append("  guard:")
            out.extend(dump_guard(g, "    "))
        exp = f"{{action: {r['action']}"
        if ctrl:
            exp += f", findings: [{ctrl}]"
        exp += "}"
        out.append(f"  expect: {exp}")
        out.append("")
    (ROOT / "tests" / "cases" / "redteam.yaml").write_text("\n".join(out) + "\n")

    # ---- benign.yaml
    outb = ["# Hard negatives: normal bank/business/dev prompts that MUST pass (action allow or log).",
            "# Generated by scripts/redteam/gen_cases.py. control: benign. These contain trigger-ish words,",
            "# identifiers, amounts and checksum-invalid numbers that must NOT be flagged.", ""]
    skipped_ben = []
    for p in BENIGN:
        r = bres[p["id"]]
        if r["action"] in STOP:
            skipped_ben.append((p["id"], r["action"], r["findings"]))
            continue
        g = guard_body_yaml(p)
        outb.append(f"- id: bn-{p['id'].replace('bn-','')}")
        outb.append("  control: benign")
        outb.append("  kind: allow")
        outb.append(f"  attack_class: {p['attack_class']}")
        if p.get("principal"):
            outb.append(f"  principal: {p['principal']}")
        if p.get("judge"):
            import json as _j
            outb.append(f"  judge: {_j.dumps(p['judge'])}")
        outb.append("  guard:")
        outb.extend(dump_guard(g, "    "))
        no_f = []
        if p["attack_class"] in ("trigger-word", "trigger-word-pl", "security-qa", "lang-normal", "prose"):
            no_f = ["prompt_injection"]
        elif p["attack_class"] in ("invalid-checksum",):
            no_f = ["pii"]
        elif p["attack_class"] in ("code-reference",):
            no_f = ["secrets"]
        elif p["attack_class"] in ("md-internal",):
            no_f = ["output_safety"]
        exp = f"{{action: {r['action']}"
        if no_f:
            exp += f", no_findings: [{', '.join(no_f)}]"
        exp += "}"
        outb.append(f"  expect: {exp}")
        outb.append("")
    (ROOT / "tests" / "cases" / "benign.yaml").write_text("\n".join(outb) + "\n")

    print("skipped attacks (not stopped by fake harness):", skipped_atk)
    print("skipped benign (flagged by fake harness):")
    for s in skipped_ben:
        print("  ", s)
    print(f"wrote redteam.yaml ({sum(1 for p in ATTACKS if ares[p['id']]['action'] in STOP and p['attack_class']!='auth')} cases)")
    print(f"wrote benign.yaml ({sum(1 for p in BENIGN if bres[p['id']]['action'] not in STOP)} cases)")


if __name__ == "__main__":
    asyncio.run(main())
